version: '2'
services:
  web:
    image: fluvip/chat_messenger:v1
    build: .
    command: mix phx.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "5432:5432"
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    links:
      - db:db
      - rabbitmq:rabbitmq
  db:
    image: postgres:9.6
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER = "postgres"
      - POSTGRES_PASSWORD = "postgres"
      - POSTGRES_HOST = "db"
      - POSTGRES_PORT = 5432
  rabbitmq:
    image: rabbitmq
    ports:
      - "15673:15673"
      - "5673:5673"
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./conf/myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
